id: '17164651336500.8562237080702915'
kind: workflow
name: getMapValues
nameConfigured: true
steps:
  - id: '17164651373690.6286338641268991'
    type: customAsyncCode
    name: code
    params:
      - type: asyncCode
        value: ./code.js
        valueType: interpolatedValue
        interpolationType: code
    level: 0
    fallthroughError: false
    isChanged: true
mode: manual
modeConfigured: false
parentPageId: '1'
config:
  shouldConfirm: false
  confirmMessage: Are you sure you'd like to proceed with "{{actions.getMapValues.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.getMapValues.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: true
  errorToast: Action "{{actions.getMapValues.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
selected: true
configured: true
